### ISSUE TITLE
BioStor creator id 50946, L. E. McKinney, used for 2 separate authors

### ISSUE THREAD

**Issue by swlny** [rdmpage/biostor#101]
FYI. This problem was reported to BHL by a user.  BHL creator record 64536 was contributed to BHL by BioStor. Name was given as L. E. McKinney.  Two articles were attributed to this author.  One was written by Laurie E. McKinney and the other by Landon E. McKinney. Solved in BHL by attributing BHL article 175968 (BioStor 167769) to Landon E. McKinney, existing BHL creator 166950. 
Hope that this is making sense.

**Comment by rdmpage** [comment]
@swlny Thanks for spotting this, I've updated BioStor 167769 to `Landon E. McKinney`.
