### ISSUE TITLE
"On some new genera of the class Myriapoda" incorrect PDF generation

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#103]
"On some new genera of the class Myriapoda"
https://www.biodiversitylibrary.org/part/244439
https://biostor.org/reference/236209

This may be a new type of error, as page range is correct in the metadata (177-181) and also shows no anomaly in BHL. However, the resulting PDF is truncated on page 180.

Please, document this anomaly.

**Comment by rdmpage** [comment]
This looks like a BHL issue, perhaps leave feedback on their site asking them to regenerate the PDF.
