### ISSUE TITLE
Die Copulationsfüsse der Polydesmiden PDF improvement

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#104]
Happy New Year, Rod!
The PDF of the article "[Die Copulationsfüsse der Polydesmiden](https://www.biodiversitylibrary.org/part/234416)" does not contain the plates. Extending the PDF generation to [this blank page](https://www.biodiversitylibrary.org/page/35767417) will solve the issue.

**Comment by rdmpage** [comment]
@Archilegt Happy New Year to you too. I've fixed this in BioStor, the changes should appear in on BHL in a day or so.
