### ISSUE TITLE
Attems 1897 (publication 7) fix

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#105]
Please, for [BHL part 54310](https://www.biodiversitylibrary.org/part/54310) fix:
Verbatim author: Attems, Carl Grafen
Pagination: To be extended anteriorly to [page 471](https://www.biodiversitylibrary.org/page/16140223).

Plates XXI-XXIV also missing. Article ends on left side page 536. Add right side plate XXI (https://www.biodiversitylibrary.org/page/16140433) and extend to right side plate XXIV (https://www.biodiversitylibrary.org/page/16140438).
Please, preserve blank pages in between.

**Comment by rdmpage** [comment]
@Archilegt I've updated this in BioStor, the changes should appear in BHL in a day or two
