### ISSUE TITLE
Bulk update: Cook (1896) Proc. USNM Vol. 18

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#106]
This update will most likely need support on the Smithsonian Institution side.  
  
Cook, O. F. (1896): Two new diplopod Myriapoda of the genus _Oxydesmus_ from the Congo. _Proceedings of the United States National Museum_, 18 (1036): 47–52. https://www.biodiversitylibrary.org/page/7733019 
Remarks:
Not yet individualized. It needs BHL part URL and a SI DOI.
Requested SI DOI: https://doi.org/10.5479/si.00963801.18-1036.47
  
Cook, O. F. (1896): _Priodesmus_, a new genus of Diplopoda from Surinam. _Proceedings of the United States National Museum_, 18 (1037): 53–57 + pl. I. https://www.biodiversitylibrary.org/page/7733013
Remarks:
Not yet individualized. Include Page 58 (blank). Include plate I but the following blank page is not needed.
It needs BHL part URL and a SI DOI.
Requested SI DOI: https://doi.org/10.5479/si.00963801.18-1037.53

Cook, O. F. (1896): On _Geophilus attenuatus_, Say, of the class Chilopoda. _Proceedings of the United States National Museum_, 18 (1038): 59–62. https://doi.org/10.5479/si.00963801.18-1038.59
Remarks:
"Ceophilus" needs to be corrected to _Geophilus_.  As it has a SI DOI, the title in BHL may need to be updated directly by BHL staff.

Cook, O. F. (1896): An arrangement of the Geophilidæ, a family of Chilopoda. _Proceedings of the United States National Museum_, 18 (1039): 63–75. https://doi.org/10.5479/si.00963801.18-1039.63
Remarks:
Without æ ligature in the title but this is not a must, at least from my side. There is a comma missing after Geophilidæ that needs fixing.  As it has a SI DOI, the title in BHL may need to be updated directly by BHL staff.

Cook, O. F. (1896): East African Diplopoda of the suborder Polydesmoidea, collected by Mr. William Astor Chanler. _Proceedings of the United States National Museum_, 18 (1042): 81–112 + pls. II-VI. https://doi.org/10.5479/si.00963801.18-1042.81
Remarks:
There is a space missing between “Mr.” and “William”. As it has a SI DOI, the title in BHL may need to be updated directly by BHL staff.

**Comment by rdmpage** [comment]
@Archilegt I've added the one missing article ("Priodesmus, a new genus of Diplopoda from Surinam" is already in BioStor). Re updating metadata associated with DOIs, this isn't something that I can do.

**Comment by Archilegt** [comment]
@mlichtenberg, please check this out.

**Comment by mlichtenberg** [comment]
In general, requests for metadata updates should be sent to BHL staff via the BHL feedback form.  If you send them to me, I'm just going to pass them on to staff (not the most efficient use of my time).

In this case, edits to these articles can be done in BioStor.  If they had BHL-assigned DOIs, then the updates would need to be done within BHL.  However, these are SI-assigned DOIs, so changes in BioStor should transfer into BHL.

The idea behind this is that once BHL assigns a DOI, BHL wants to have complete control over the metadata.  So changes from outside BHL are not accepted.  On the other hand, BHL does not control the metadata if the DOI is not assigned by BHL, so in that case outside updates are accepted.

**Comment by rdmpage** [comment]
@Archilegt 

- `Two new diplopod Myriapoda of the genus Oxydesmus from the Congo` Fixed a typo in the title

- `Priodesmus, a new genus of Diplopoda from Surinam` Added as mentioned above

- `On Geophilus attenuatus, Say, of the class Chilopoda` This is correct in BioStor

- `An arrangement of the Geophilidæ, a family of Chilopoda` Correct in BioStor

- `East African Diplopoda of the suborder Polydesmoidea, collected by Mr. William Astor Chanler` Correct in BioStor


For the articles that are correct in BioStor but not BHL this may be an updating issue, I've tweaked each reference such that an update should be triggered. Check back in a day or two to see what happens.

Note that any errors in CrossRef metadata are outside my control.
