### ISSUE TITLE
Pocock (1891) BioStor and BHL "same as" duplicates

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#107]
Screenshot taken from https://www.biodiversitylibrary.org/part/63205

![image](https://user-images.githubusercontent.com/60008120/221185285-8f62f619-aee2-415d-9c2b-1801eb388115.png)

Screenshot shows the duplicates that I am referring to. Duplication likely due to non-matching page intervals.
Incorrect page interval: 51-58.
Correct page interval: 51-68 (+ pl. IV)

If desired, add plates and DOIs to the two parts of the work:
Pocock (1891) pp. 51-68 (+ pl. IV). https://doi.org/10.1080/00222939109460577
Link to plate IV: https://www.biodiversitylibrary.org/page/25165028
Pocock (1891) pp. 221-231 (+ pl. V). https://doi.org/10.1080/00222939109460598
Link to plate V: https://www.biodiversitylibrary.org/page/25165030

References in Myriatrix:
Pocock (1891) pp. 51-68 (+ pl. IV). 
https://myriatrix.myspecies.info/content/notes-synonymy-some-species-scolopendridæ-descriptions-new-genera-and-species-group-0
Pocock (1891) pp. 221-231 (+ pl. V). 
https://myriatrix.myspecies.info/content/notes-synonymy-some-species-scolopendridæ-descriptions-new-genera-and-species-group

**Comment by rdmpage** [comment]
Thanks @Archilegt I've updated the two duplicates to have the same pagination and DOI, and added plates to the two 51-68 articles and the one 221-231 article.
