### ISSUE TITLE
Fixes to Gervais (1837)

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#109]
**Fixes to Gervais (1837):**
- Add plate 4 (https://www.biodiversitylibrary.org/page/2255067) to PDF formation of Gervais (1837) (https://www.biodiversitylibrary.org/part/28836).
- See if title can be corrected to "Études pour servir à l’histoire naturelle des Myriapodes".

**Questions for learning:**
- How is the "Series / Issue" field modeled? In this case having it with the value "Series: 2" under the "Volume" field is a bit confusing, as the Series is hierarchically superior to the Volume in this case.
- Sections A and C of plate 4  (https://www.biodiversitylibrary.org/page/2255067) correspond to non-Myriapoda articles. Can a plate be included in the PDF formation of more than one article?

**Comment by rdmpage** [comment]
@Archilegt I've added plate 4 to this article, it should appear in the BHL PDF shortly. I've also tweaked the title.

In answer to the question about plates being included in more than one PDF, the answer is yes. This happens all the time with pages in journals where articles start on the same page as the previous article ends.

Re the modelling of Series/issue, this is a BHL interface thing, you'll have to take it up with them. I suspect they lumped both together as qualifiers for volume for display purposes.
