### ISSUE TITLE
Kohlrausch (1881) update: Add plates to PDF generation

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#111]
Kohlrausch (1881) (https://doi.org/10.5962/bhl.part.13209) PDF generation needs adding:
Plate IV: https://www.biodiversitylibrary.org/page/6378522
Plate V: https://www.biodiversitylibrary.org/page/6378524

**Comment by swlny** [comment]
I have made this update in BHL. Susan

**Comment by rdmpage** [comment]
@Archilegt  @swlny Updated in BioStor. Same comment applies as for https://github.com/rdmpage/biostor/issues/99#issuecomment-1501071990 I think to avoid duplication of effort issues with BioStor-sourced metadata are best resolved on BioStor.
