### ISSUE TITLE
Pocock (1896) reference re-deployment + plate addition

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#112]
Please, re-deploy Pocock (1896) reference (https://www.biodiversitylibrary.org/part/58471) on the Smithsonian Libraries copy (https://www.biodiversitylibrary.org/page/16007297). The latter version is complete, with plates.
Please, add plate XVIII (https://www.biodiversitylibrary.org/page/16007383) to PDF generation.
Please, edit title to "On the Scorpions, Centipedes, and Millipedes obtained by Dr. Gregory on his Expedition to Mount Kenia, East Africa".

**Comment by rdmpage** [comment]
@Archilegt I've added the plate to the article using https://www.biodiversitylibrary.org/page/18662360. Both scans appear to be complete, they just differ on where the plates are in the scan.

I've not changed the title as this is the one supplied by CrossRef via the current publisher (Taylor and Francis). If CrossRef has data I tend to default to that as the source of "truth".
