### ISSUE TITLE
Mémoires de la Société neuchâteloise des Sciences naturelles, 5 needs aggregation

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#113]
Mémoires de la Société neuchâteloise des Sciences naturelles, 5. 
Contributed by: New York Botanical Garden, LuEsther T. Mertz Library
Is BHL bibliography: https://www.biodiversitylibrary.org/bibliography/46309
Has DOI: https://doi.org/10.5962/bhl.title.46309
Is BHL item: https://www.biodiversitylibrary.org/item/100169
This is the primary scan chosen for Myriatrix literature recording and scientific name linking to exact pages.

Needs aggregation under:
Is BHL bibliography: https://www.biodiversitylibrary.org/bibliography/10027
Where existing volume 5:
Is BHL item: https://www.biodiversitylibrary.org/item/192544
Contributed by: Smithsonian Libraries
Has DOI: No.

**Comment by rdmpage** [comment]
@Archilegt This is an aspect of BHL that you'd need to discuss with BHL itself. Because it's a federation across multiple libraries the "same" content may be handled differently. Individual items may be treated as monographs, or as items within a journal, or both.
