### ISSUE TITLE
Duplicated DOI: Traite de zoologie concrète

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#114]
Traite de zoologie concrète

Old:
https://www.biodiversitylibrary.org/bibliography/11672
https://doi.org/10.5962/bhl.title.11672

New:
https://www.biodiversitylibrary.org/bibliography/104948
https://doi.org/10.5962/bhl.title.104948

**Comment by rdmpage** [comment]
@Archilegt This happened a few times when BHL was assigning DOIs to titles. I suggest leaving feedback with BHL and see if you get a response.

**Comment by Archilegt** [comment]
Feedback sent to BHL. Very time-consuming to say every time that I am not a robot and then waste time clicking on "motorcycle squares". BHL needs a virtual research environment for the users to directly contribute and curate metadata, as well as for correcting the OCR itself. Anything done by email will be a huge waste of time for 2+ people.

**Comment by rdmpage** [comment]
@Archilegt Nice idea, requires resources to create and run, and my understanding is that BHL doesn't have those at the moment.
