### ISSUE TITLE
The Nautilus, v.79-80 (1965-1967)

### ISSUE THREAD

**Issue by swlny** [rdmpage/biostor#115]
The digital copy of v.79 of this publication in BHL was found to have missing pages and a ticket was opened by a researcher to report the problem. A new digital copy of v.79-80 was provided by SLA and added to BHL. I was asked to move all articles defined in the old copy of v.79 (BHL item 34858) to the new, complete copy (BHL item 196056). I was asked to "darken" item 34858 after moving the articles. While doing this work, I noticed that most of these articles lacked authors and added author information. I also tweaked a couple of minor problems with titles. I am attaching a tsv file containing the article metadata updates in case you want them for BioStor. BHL is not dependent on the changes being made in BioStor and passed to BHL. It's entirely up to you if you want the updates.  I'll wait a week or two to "darken" item 34858. Best wishes!

**Comment by swlny** [comment]
[The Nautilus, modifications - Sheet1.txt](https://github.com/rdmpage/biostor/files/13593278/The.Nautilus.modifications.-.Sheet1.txt)

**Comment by rdmpage** [comment]
Hi @swlny, OK I've moved the BioStor articles across to the new item. This whole process is a mess :(

**Comment by swlny** [comment]
So sorry... Happy to do anything in my power to minimize the mess.

**Comment by rdmpage** [comment]
No worries, your report of the change was detailed and helpful. It’s just the whole replacing of scanned items and having to move articles is clunky. Plus I’m being grumpy 😉

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
