### ISSUE TITLE
OpenURL resolver

### ISSUE THREAD

**Issue by kbseah** [rdmpage/biostor#117]
Hello, I am looking for the OpenURL resolver that is described in the 2011 paper. The link http://biostor.org/openurl/ leads to a 404 page. Is the resolver still active under a different address, or has that service been discontinued? Thanks!

**Comment by rdmpage** [comment]
@kbseah Hi, the OpenURL feature has been discontinued as BioStor has been split into an external facing web site and a local use only tool to add articles to BHL.

However, BioStor does support the Open Refine reconciliation service, see http://biostor.org/match.html. This isn't well documented, but the endpoint is `https://biostor.org/reconcile?queries=` where the parameter is the query object expected by the reconcilaition service. For the web page example, the parameter is:

```json
{
    "q0": {
        "query": "Strand, E. 1912. Ein neueres Werk über afrikanische Bienen kritisch besprochen. Archiv für Naturgeschichte 78 126-144",
        "limit": 3
    },
    "q1": {
        "query": "Strand, E. 1913. Bestimmungstabelle nebst weiteren Beiträgen zur Kenntnis afrikanischer Nomia-Arten. Archiv für Naturgeschichte A79 121-144",
        "limit": 3
    },
    "q2": {
        "query": "Michener, C.D. 1978. The parasitic groups of Halictidae (Hymenoptera, Apoidea). The University of Kansas Science Bulletin 51 291-339",
        "limit": 3
    },
    "q3": {
        "query": "Michener, C.D. and T.L. Griswold. 1994. The classification of Old World Anthidiini (Hymenoptera, Megachilidae). The University of Kansas Science Bulletin 55 299-327",
        "limit": 3
    }
}
```

Hope this helps.

**Comment by kbseah** [comment]
This is useful, thank you!

For context, I was encountering citations in Wikidata to articles which would fall within the scope of Biostor, but wasn't sure if there was a pipeline for users to suggest new articles to add.

**Comment by rdmpage** [comment]
@kbseah  There's not an official pipeline for suggestions, but if you have them feel free to add them as issues. If you have bibliographic metadata that's ideal, by default I work with RIS but can use pretty much anything.

**Comment by kbseah** [comment]
Thanks! I'll post a ticket when I accumulate a decent number.
