### ISSUE TITLE
Index Entomologica Americana

### ISSUE THREAD

**Issue by trosesandler** [rdmpage/biostor#26]
Rod

We'd like to index 3 journals from the New York Entomological Society
1.  Entomologica Americana (v.1 (1885) to v.49 (1975)) http://biodiversitylibrary.org/bibliography/9429 
2.  Journal of the New York Entomological Society (v.1 (1893) to v.107 (1999)) http://biodiversitylibrary.org/bibliography/8089 
3.  Bulletin of the Brooklyn Entomological Society (v.1 (1878) to v.60 (1965)) http://biodiversitylibrary.org/bibliography/16211 

Lets start with Entomologica Americana.  Some of this has been indexed already by BioStor so I'm trying to figure out where we need to gap fill.  A BHL staff member informed me that Web of Science has 749 citations for Entomological Americana.  Since I don't have access to Web of Science myself the staff member would need to download them for me.  What I'm wondering is do you have access to Web of Science and are you able to verify which citations they have vs those in BioStor and BHL?  If its easier I can have the staff member download the citations and we can send to you.  Let me know what you think is most efficient.
Trish

**Comment by rdmpage** [comment]
@trosesandler I have access to Web of Science here. I guess what I'll need to look at is providing a way for BHL to easily see exactly what articles have already been done. For example, I could add a feature whereby you upload a RIS or Web of Science file and each reference is checked against BioStor. Would this be useful?

**Comment by trosesandler** [comment]
Rod

that does sound like a very useful feature!  So for Entomologica Americana
and other NYES publications sounds like you would prefer that we down the
citations, compare them with BioStor then send you those citations where
there wasn't a match yes?  That's fine, but since we are limited by the 500
record limitation it will require several downloads, merging and deduping
before we can have a file ready to compare with BioStor.  I presume this
would be the same process for you right (i.e. you don't have a workaround
to that in Web of Science?)

Trish

**Comment by rdmpage** [comment]
I do this manually. You shouldn't need to deduce if you download records 1-500, 501-1000, etc.

**Comment by trosesandler** [comment]
Hello Rod,

Just following up on this conversation - I wasn't sure if I should wait until you had this comparison feature added or just hand off the files from Web of Science to you?  Let me know how you'd like to proceed.

**Comment by rdmpage** [comment]
@trosesandler Realistically I'm not in a position to build such a feature anytime soon, so if you have Web of Science files by all means send them on and I can add the articles to BioStor..
