### ISSUE TITLE
Question about italics for botanical scientific names.

### ISSUE THREAD

**Issue by suwiding** [rdmpage/biostor#30]
@rdmpage  I've been given thousands of good citations for Phytologia, ISSN 0031-9430, from the Index of American Botanical Literature.  There's a potential for many more citations from this source.  In the csv files that I received from the system administrator (EMU at NYBG), the article titles contain mark-up to cause scientific names to be presented on the UI in italics as they should be.  For example, I was given:
A new variety of &lt;Astragalus hyalilnus&gt; (Fabaceae) from Wyoming  
Italics are used when this is displayed in IABL.  See http://sweetgum.nybg.org/science/iabl/iabl_details.php?irn=468377
In BHL:  http://www.biodiversitylibrary.org/part/184351
In BioStor:  http://biostor.org/reference/175861

In BioStor and BHL, it seems that we have no way to display marked up text in italics.  Is this true? I can easily strip out this markup using a regular expression and OpenRefine but it seems a shame to do so.  A subject matter expert (NYBG botanist) did a lot of work to markup the scientific names and it's the right thing to do. If I discard the markup now we'll probably never get it back...  I'd very much like your advice on this.

**Comment by rdmpage** [comment]
@suwiding I suggest keeping the markup. Is it in HTML form (e.g., <i>Astragalus hyalilnus</i>) or <Astragalus hyalilnus> which is non-standard. I've ignored formatting to date in BioStor, but could incorporate it if desired. I agree that there's no point removing markup that adds value.
