### ISSUE TITLE
Replaced BHL items

### ISSUE THREAD

**Issue by rdmpage** [rdmpage/biostor#31]
Via email from @mlichtenberg:

> Over time, re-scans of books have resulted in BHL items being replaced with other items.  This has resulted in about 2500 articles in BHL and BioStor that are associated with about 100 inactive items.  (For example, http://biostor.org/reference/134917.)
>
> At the end of this message is a list of no-longer-active BHL item IDs along with their replacement IDs.  Given this list, would it be difficult for you to reprocess the articles that are attached to those items so that they are reassigned to the correct BHL item and page IDs?
>
> If you could do that, it would fix both BioStor and BHL.  BHL should pick up the updates the next time BioStor data is harvested.

```
ID            Replaced By
13942    54265
13961    54271
13976    86336
13978    54725
43946    130127
13936    54259
13950    54269
13953    54267
13967    89035
14000    87380
14017    89038
14018    89037
119060  211380
13946    54274
13957    54437
13971    65863
13996    89024
14014    89030
14021    87374
14400    86341
46567    13718
13941    54264
13945    86340
13958    54743
13975    86335
13992    65873
14009    89021
13948    54272
13955    54435
13962    54732
13991    54728
13998    54735
14005    87377
14012    89029
36407    133894
13947    54273
13956    54436
13981    86337
13990    54727
14015    89031
53247    55101
13949    54270
13954    54266
13979    54721
13988    65870
14013    89405
14022    87373
81625    34159
105675  101305
119064  212127
13935    54258
13968    89036
13985    65867
13986    65868
14003    54734
13939    54262
13964    54730
13989    65872
14007    87375
13938    54261
13965    54741
13974    86342
126229  127883
13943    54717
13960    54733
13977    54724
13994    89027
14011    54744
50997    183290
149492  182036
12974    54720
13959    54742
13993    89026
13995    89028
14008    89020
14010    89022
81620    105193
105799  101303
13951    54719
13952    54268
13966    54745
14001    87379
14002    54746
46849    183041
13937    54260
13973    54723
13980    54726
13987    65869
14016    87378
25429    202453
13940    54263
13963    54731
13997    89023
13999    89032
14004    89033
14006    87376
105316  100979
13933    54249
13934    54257
13969    65861
13970    65862
13983    65865
13984    65866
14019    86338
14020    86343
20991    100809
105673  101293
```

**Comment by rdmpage** [comment]
Related issue https://github.com/rdmpage/biostor/issues/21

**Comment by crowleyb** [comment]
Hi Rod, it's Bianca and I found another one for this list: Item ID 46651 replaced by 13721

**Comment by rdmpage** [comment]
@crowleyb Thanks, I'll try amdake progress on this I'm the next few days.

Sent from my iPhone

		_____________________________

**Comment by crowleyb** [comment]
And here's a few more: 
ItemID 46224 replaced by 13712
ItemID 46220 replaced by 13711
ItemID 46587 replaced by 13692

**Comment by rdmpage** [comment]
List of replaced items as a task list, see https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

- [ ] http://biodiversitylibrary.org/item/13942 replaced by http://biodiversitylibrary.org/item/54265
- [ ] http://biodiversitylibrary.org/item/13961 replaced by http://biodiversitylibrary.org/item/54271
- [ ] http://biodiversitylibrary.org/item/13976 replaced by http://biodiversitylibrary.org/item/86336
- [ ] http://biodiversitylibrary.org/item/13978 replaced by http://biodiversitylibrary.org/item/54725
- [ ] http://biodiversitylibrary.org/item/43946 replaced by http://biodiversitylibrary.org/item/130127
- [ ] http://biodiversitylibrary.org/item/13936 replaced by http://biodiversitylibrary.org/item/54259
- [ ] http://biodiversitylibrary.org/item/13950 replaced by http://biodiversitylibrary.org/item/54269
- [ ] http://biodiversitylibrary.org/item/13953 replaced by http://biodiversitylibrary.org/item/54267
- [ ] http://biodiversitylibrary.org/item/13967 replaced by http://biodiversitylibrary.org/item/89035
- [ ] http://biodiversitylibrary.org/item/14000 replaced by http://biodiversitylibrary.org/item/87380
- [ ] http://biodiversitylibrary.org/item/14017 replaced by http://biodiversitylibrary.org/item/89038
- [ ] http://biodiversitylibrary.org/item/14018 replaced by http://biodiversitylibrary.org/item/89037
- [ ] http://biodiversitylibrary.org/item/119060 replaced by http://biodiversitylibrary.org/item/211380
- [ ] http://biodiversitylibrary.org/item/13946 replaced by http://biodiversitylibrary.org/item/54274
- [ ] http://biodiversitylibrary.org/item/13957 replaced by http://biodiversitylibrary.org/item/54437
- [ ] http://biodiversitylibrary.org/item/13971 replaced by http://biodiversitylibrary.org/item/65863
- [ ] http://biodiversitylibrary.org/item/13996 replaced by http://biodiversitylibrary.org/item/89024
- [ ] http://biodiversitylibrary.org/item/14014 replaced by http://biodiversitylibrary.org/item/89030
- [ ] http://biodiversitylibrary.org/item/14021 replaced by http://biodiversitylibrary.org/item/87374
- [ ] http://biodiversitylibrary.org/item/14400 replaced by http://biodiversitylibrary.org/item/86341
- [ ] http://biodiversitylibrary.org/item/46567 replaced by http://biodiversitylibrary.org/item/13718
- [ ] http://biodiversitylibrary.org/item/13941 replaced by http://biodiversitylibrary.org/item/54264
- [ ] http://biodiversitylibrary.org/item/13945 replaced by http://biodiversitylibrary.org/item/86340
- [ ] http://biodiversitylibrary.org/item/13958 replaced by http://biodiversitylibrary.org/item/54743
- [ ] http://biodiversitylibrary.org/item/13975 replaced by http://biodiversitylibrary.org/item/86335
- [ ] http://biodiversitylibrary.org/item/13992 replaced by http://biodiversitylibrary.org/item/65873
- [ ] http://biodiversitylibrary.org/item/14009 replaced by http://biodiversitylibrary.org/item/89021
- [ ] http://biodiversitylibrary.org/item/13948 replaced by http://biodiversitylibrary.org/item/54272
- [ ] http://biodiversitylibrary.org/item/13955 replaced by http://biodiversitylibrary.org/item/54435
- [ ] http://biodiversitylibrary.org/item/13962 replaced by http://biodiversitylibrary.org/item/54732
- [ ] http://biodiversitylibrary.org/item/13991 replaced by http://biodiversitylibrary.org/item/54728
- [ ] http://biodiversitylibrary.org/item/13998 replaced by http://biodiversitylibrary.org/item/54735
- [ ] http://biodiversitylibrary.org/item/14005 replaced by http://biodiversitylibrary.org/item/87377
- [ ] http://biodiversitylibrary.org/item/14012 replaced by http://biodiversitylibrary.org/item/89029
- [ ] http://biodiversitylibrary.org/item/36407 replaced by http://biodiversitylibrary.org/item/133894
- [ ] http://biodiversitylibrary.org/item/13947 replaced by http://biodiversitylibrary.org/item/54273
- [ ] http://biodiversitylibrary.org/item/13956 replaced by http://biodiversitylibrary.org/item/54436
- [ ] http://biodiversitylibrary.org/item/13981 replaced by http://biodiversitylibrary.org/item/86337
- [ ] http://biodiversitylibrary.org/item/13990 replaced by http://biodiversitylibrary.org/item/54727
- [ ] http://biodiversitylibrary.org/item/14015 replaced by http://biodiversitylibrary.org/item/89031
- [ ] http://biodiversitylibrary.org/item/53247 replaced by http://biodiversitylibrary.org/item/55101
- [ ] http://biodiversitylibrary.org/item/13949 replaced by http://biodiversitylibrary.org/item/54270
- [ ] http://biodiversitylibrary.org/item/13954 replaced by http://biodiversitylibrary.org/item/54266
- [ ] http://biodiversitylibrary.org/item/13979 replaced by http://biodiversitylibrary.org/item/54721
- [ ] http://biodiversitylibrary.org/item/13988 replaced by http://biodiversitylibrary.org/item/65870
- [ ] http://biodiversitylibrary.org/item/14013 replaced by http://biodiversitylibrary.org/item/89405
- [ ] http://biodiversitylibrary.org/item/14022 replaced by http://biodiversitylibrary.org/item/87373
- [ ] http://biodiversitylibrary.org/item/81625 replaced by http://biodiversitylibrary.org/item/34159
- [ ] http://biodiversitylibrary.org/item/105675 replaced by http://biodiversitylibrary.org/item/101305
- [ ] http://biodiversitylibrary.org/item/119064 replaced by http://biodiversitylibrary.org/item/212127
- [ ] http://biodiversitylibrary.org/item/13935 replaced by http://biodiversitylibrary.org/item/54258
- [ ] http://biodiversitylibrary.org/item/13968 replaced by http://biodiversitylibrary.org/item/89036
- [ ] http://biodiversitylibrary.org/item/13985 replaced by http://biodiversitylibrary.org/item/65867
- [ ] http://biodiversitylibrary.org/item/13986 replaced by http://biodiversitylibrary.org/item/65868
- [ ] http://biodiversitylibrary.org/item/14003 replaced by http://biodiversitylibrary.org/item/54734
- [ ] http://biodiversitylibrary.org/item/13939 replaced by http://biodiversitylibrary.org/item/54262
- [ ] http://biodiversitylibrary.org/item/13964 replaced by http://biodiversitylibrary.org/item/54730
- [ ] http://biodiversitylibrary.org/item/13989 replaced by http://biodiversitylibrary.org/item/65872
- [ ] http://biodiversitylibrary.org/item/14007 replaced by http://biodiversitylibrary.org/item/87375
- [ ] http://biodiversitylibrary.org/item/13938 replaced by http://biodiversitylibrary.org/item/54261
- [ ] http://biodiversitylibrary.org/item/13965 replaced by http://biodiversitylibrary.org/item/54741
- [ ] http://biodiversitylibrary.org/item/13974 replaced by http://biodiversitylibrary.org/item/86342
- [ ] http://biodiversitylibrary.org/item/126229 replaced by http://biodiversitylibrary.org/item/127883
- [ ] http://biodiversitylibrary.org/item/13943 replaced by http://biodiversitylibrary.org/item/54717
- [ ] http://biodiversitylibrary.org/item/13960 replaced by http://biodiversitylibrary.org/item/54733
- [ ] http://biodiversitylibrary.org/item/13977 replaced by http://biodiversitylibrary.org/item/54724
- [ ] http://biodiversitylibrary.org/item/13994 replaced by http://biodiversitylibrary.org/item/89027
- [ ] http://biodiversitylibrary.org/item/14011 replaced by http://biodiversitylibrary.org/item/54744
- [ ] http://biodiversitylibrary.org/item/50997 replaced by http://biodiversitylibrary.org/item/183290
- [ ] http://biodiversitylibrary.org/item/149492 replaced by http://biodiversitylibrary.org/item/182036
- [ ] http://biodiversitylibrary.org/item/12974 replaced by http://biodiversitylibrary.org/item/54720
- [ ] http://biodiversitylibrary.org/item/13959 replaced by http://biodiversitylibrary.org/item/54742
- [ ] http://biodiversitylibrary.org/item/13993 replaced by http://biodiversitylibrary.org/item/89026
- [ ] http://biodiversitylibrary.org/item/13995 replaced by http://biodiversitylibrary.org/item/89028
- [ ] http://biodiversitylibrary.org/item/14008 replaced by http://biodiversitylibrary.org/item/89020
- [ ] http://biodiversitylibrary.org/item/14010 replaced by http://biodiversitylibrary.org/item/89022
- [ ] http://biodiversitylibrary.org/item/81620 replaced by http://biodiversitylibrary.org/item/105193
- [ ] http://biodiversitylibrary.org/item/105799 replaced by http://biodiversitylibrary.org/item/101303
- [ ] http://biodiversitylibrary.org/item/13951 replaced by http://biodiversitylibrary.org/item/54719
- [ ] http://biodiversitylibrary.org/item/13952 replaced by http://biodiversitylibrary.org/item/54268
- [ ] http://biodiversitylibrary.org/item/13966 replaced by http://biodiversitylibrary.org/item/54745
- [ ] http://biodiversitylibrary.org/item/14001 replaced by http://biodiversitylibrary.org/item/87379
- [ ] http://biodiversitylibrary.org/item/14002 replaced by http://biodiversitylibrary.org/item/54746
- [ ] http://biodiversitylibrary.org/item/46849 replaced by http://biodiversitylibrary.org/item/183041
- [ ] http://biodiversitylibrary.org/item/13937 replaced by http://biodiversitylibrary.org/item/54260
- [ ] http://biodiversitylibrary.org/item/13973 replaced by http://biodiversitylibrary.org/item/54723
- [ ] http://biodiversitylibrary.org/item/13980 replaced by http://biodiversitylibrary.org/item/54726
- [ ] http://biodiversitylibrary.org/item/13987 replaced by http://biodiversitylibrary.org/item/65869
- [ ] http://biodiversitylibrary.org/item/14016 replaced by http://biodiversitylibrary.org/item/87378
- [ ] http://biodiversitylibrary.org/item/25429 replaced by http://biodiversitylibrary.org/item/202453
- [ ] http://biodiversitylibrary.org/item/13940 replaced by http://biodiversitylibrary.org/item/54263
- [ ] http://biodiversitylibrary.org/item/13963 replaced by http://biodiversitylibrary.org/item/54731
- [ ] http://biodiversitylibrary.org/item/13997 replaced by http://biodiversitylibrary.org/item/89023
- [ ] http://biodiversitylibrary.org/item/13999 replaced by http://biodiversitylibrary.org/item/89032
- [ ] http://biodiversitylibrary.org/item/14004 replaced by http://biodiversitylibrary.org/item/89033
- [ ] http://biodiversitylibrary.org/item/14006 replaced by http://biodiversitylibrary.org/item/87376
- [ ] http://biodiversitylibrary.org/item/105316 replaced by http://biodiversitylibrary.org/item/100979
- [ ] http://biodiversitylibrary.org/item/13933 replaced by http://biodiversitylibrary.org/item/54249
- [ ] http://biodiversitylibrary.org/item/13934 replaced by http://biodiversitylibrary.org/item/54257
- [ ] http://biodiversitylibrary.org/item/13969 replaced by http://biodiversitylibrary.org/item/65861
- [ ] http://biodiversitylibrary.org/item/13970 replaced by http://biodiversitylibrary.org/item/65862
- [ ] http://biodiversitylibrary.org/item/13983 replaced by http://biodiversitylibrary.org/item/65865
- [ ] http://biodiversitylibrary.org/item/13984 replaced by http://biodiversitylibrary.org/item/65866
- [ ] http://biodiversitylibrary.org/item/14019 replaced by http://biodiversitylibrary.org/item/86338
- [ ] http://biodiversitylibrary.org/item/14020 replaced by http://biodiversitylibrary.org/item/86343
- [ ] http://biodiversitylibrary.org/item/20991 replaced by http://biodiversitylibrary.org/item/100809
- [ ] http://biodiversitylibrary.org/item/105673 replaced by http://biodiversitylibrary.org/item/101293
- [ ] http://biodiversitylibrary.org/item/46224 replaced by http://biodiversitylibrary.org/item/13712
- [ ] http://biodiversitylibrary.org/item/46220 replaced by http://biodiversitylibrary.org/item/13711
- [ ] http://biodiversitylibrary.org/item/46587 replaced by http://biodiversitylibrary.org/item/13692

**Comment by rdmpage** [comment]
@mlichtenberg @crowleyb OK, finally making progress on this. Previous comment https://github.com/rdmpage/biostor/issues/31#issuecomment-269467887 lists all the replaced items this thread mentions, and I'm ticking off each one as I update BioStor articles to point to replacement items.

**Comment by rdmpage** [comment]
OK, I think that's all the items updated.
