### ISSUE TITLE
Add Articles for Volume 30 of Zoologica, ISSN 0044-507X

### ISSUE THREAD

**Issue by suwiding** [rdmpage/biostor#40]
The final volume of this publication made it into BHL today!  I'm sending what I hope is the final set of article definitions for this title.  I added BHL start page numbers to the Notes field in the RIS file.  There is no 'Database Provider' for this publication.
[zoologica_vol_30.txt.zip](https://github.com/rdmpage/biostor/files/661936/zoologica_vol_30.txt.zip)

**Comment by rdmpage** [comment]
@suwiding Great, here are the articles in BioStor http://biostor.org/issn/0044-507X/year/1945

**Comment by rdmpage** [comment]
@suwiding If you're happy with volume 30 we can close this issue and #28

**Comment by suwiding** [comment]
I didn't mention in my first comment that the last citation in the RIS file was from volume 31 (1946).  I don't think that it was added to BioStor.  Do you know why? RIS metadata:
TY  - JOUR
AU  - Cohen, Herman
IS  - 9
N1  - 50979249
PY  - 1946
SN  - 0044-507X
SP  - 121-128
ST  - Effects of Sex Hormones on the Development of the Platyfish, Platypoecilus maculatus 
T2  - Zoologica
TI  - Effects of Sex Hormones on the Development of the Platyfish, Platypoecilus maculatus 
VL  - 31
ID  - 11553
ER  -

**Comment by rdmpage** [comment]
I skipped that as it's not in volume 30. Will add it when I get a chance.

Get Outlook for iOS




On Mon, Dec 19, 2016 at 10:38 PM +0000, "suwiding" <notifications@github.com> wrote:












I didn't mention in my first comment that the last citation in the RIS file was from volume 31 (1946).  I don't think that it was added to BioStor.  Do you know why? RIS metadata:

TY  - JOUR

AU  - Cohen, Herman

IS  - 9

N1  - 50979249

PY  - 1946

SN  - 0044-507X

SP  - 121-128

ST  - Effects of Sex Hormones on the Development of the Platyfish, Platypoecilus maculatus

T2  - Zoologica

TI  - Effects of Sex Hormones on the Development of the Platyfish, Platypoecilus maculatus

VL  - 31

ID  - 11553

ER  -

**Comment by rdmpage** [comment]
Effects of Sex Hormones on the Development of the Platyfish, Platypoecilus maculatus is added now http://biostor.org/reference/201664
