### ISSUE TITLE
BioStor ID 90301 had wrong BHL item attached

### ISSUE THREAD

**Issue by crowleyb** [rdmpage/biostor#42]
Hi Rod, Biostor ID 90301 was originally attached to item ID 19556 = v.18 (1846) but it needed to be attached instead to the second series v.18 under item ID 19544. I have corrected this in BHL, see http://www.biodiversitylibrary.org/page/2313485. Wanted to let you know to update your system just in case.

**Comment by rdmpage** [comment]
@crowleyb Thanks for spotting this, I've fixed the record in BioStor.
