### ISSUE TITLE
Incomplete (duplicate?) articles

### ISSUE THREAD

**Issue by mlichtenberg** [rdmpage/biostor#49]
BHL picked up a few new articles (BioStor IDs 50280, 50281, 50282, and 50284) missing a lot of metadata (including titles) this weekend.  Each new article includes only a single page, and in each case that page duplicates the start page of another article that was defined long ago.

You can see these articles with these API calls:

http://direct.biostor.org/itemarticles.php?item=25762
http://direct.biostor.org/itemarticles.php?item=25760

Based on the dates attached to them, it looks like these articles were actually defined in BioStor a long time ago.  Also, I have made a few changes to BHL's data harvesting process recently.  Let me know if the appearance of these articles in the API not new; maybe the BHL changes have resulted in the harvesting process no longer ignoring something that should be ignored.

**Comment by rdmpage** [comment]
Whoops, well-spotted, I've deleted these.
