### ISSUE TITLE
Add articles for Amphipacifica (ISSN 1189-9905)

### ISSUE THREAD

**Issue by rdmpage** [rdmpage/biostor#51]

**Comment by trosesandler** [comment]
Rod

I just finished uploading all 12 files for Amphipacifica today so thanks for diving into getting the articles!

**Comment by rdmpage** [comment]
Great, it’s a nice little journal. I have article metadata for a couple more articles at http://bionames.org/issn/1189-9905 <http://bionames.org/issn/1189-9905> but no other sources at the moment.

**Comment by suwiding** [comment]
Trish and Rod,
I have some volunteers that can create citations for all remaining articles.OK?

**Comment by rdmpage** [comment]
@suwiding Sounds good to me!

Get Outlook for iOS




On Sat, Jan 21, 2017 at 10:04 PM +0000, "suwiding" <notifications@github.com> wrote:












Trish and Rod,

I have some volunteers that can create citations for all remaining articles.OK?

**Comment by trosesandler** [comment]
Excellent Susan - thanks!

**Comment by suwiding** [comment]
@rdmpage  We finally finished the citations for Amphipacifica.  They're in the attached zip file.  We also spotted a problem. Year in BioStor: 205203 is 2004 but should be 2001.
[Amphipacifica_add_BioStor_and_BHL.zip](https://github.com/rdmpage/biostor/files/746539/Amphipacifica_add_BioStor_and_BHL.zip)

**Comment by rdmpage** [comment]
Thanks @suwiding I've added these articles. FYI a couple had minor errors in pagination, the BHL PageID in the file was for the page just before the start of the article. I've fixed those.
