### ISSUE TITLE
Linn. Soc. NSW v.92 volume replaced in BHL

### ISSUE THREAD

**Issue by crowleyb** [rdmpage/biostor#59]
Hi Rod, I just removed BHL item number 108670 and replaced it with 221241. 108670 = http://biostor.org/issn/0370-047X/year/1968. It was an incomplete volume (92) of the Proceedings of the Linnean Society of New South Wales digitized by MBLWHOI and just recently replaced by an SIL scanned copy. I wanted to let you know since 108670 had several articles associated. Can they be switched over to item 221241? Thank you.

**Comment by rdmpage** [comment]
@crowleyb Argh! OK will look at doing this soon(ish).

**Comment by rdmpage** [comment]
@crowleyb I've fixed this issue. It was a pain because the newly added item lacked page numbers towards the end, which meant each article had to be relocated manually. It would be great if replacement items were fully paginated when they are uploaded, this makes remapping the articles a lot easier.
