### ISSUE TITLE
Linn. Soc. NSW v.59 volume replaced

### ISSUE THREAD

**Issue by crowleyb** [rdmpage/biostor#60]
Another item replacement: 
BHL item number 108590 replaced by 223032. 
108590 = http://biostor.org/issn/0370-047X/year/1934
Lots of articles present that need to be redirected if possible

**Comment by rdmpage** [comment]
@crowleyb Argh! OK will look at doing this soon(ish). Maybe we need a script that automatically maps articles from old items to new...

**Comment by rdmpage** [comment]
@crowleyb What a pain this item is, multiple pages have the same "page number" (e.g., text and plates), this makes automating the redirection hard to do. I wish BHL would stop replacing items like this, it's creating work that I don't really need :(

**Comment by rdmpage** [comment]
Updated one article http://biostor.org/reference/67881
