### ISSUE TITLE
Replaced items list

### ISSUE THREAD

**Issue by crowleyb** [rdmpage/biostor#66]
Hi Rod, the following items in BHL have been replaced by others. The original items had segments associated with them. Is it possible on your end to redirect the existing segments or run your process again on the new items? Please see the attached.
[BHLitemsReplaced.xlsx](https://github.com/rdmpage/biostor/files/1052943/BHLitemsReplaced.xlsx)

**Comment by rdmpage** [comment]
ID | Status | Replaced By | Contributor | Active Titles | Active Items | Active Segments | Notes
-- | -- | -- | -- | -- | -- | -- | --
49733 | QA Problems | 213414 | American Museum of Natural History Library |   |   | Yes | BioStor
45725 | Removed | 87759 | Harvard University, Museum of Comparative Zoology, Ernst Mayr Library |   |   | Yes | BioStor
17635 | QA Problems | 84886 | MBLWHOI Library |   |   | Yes | BioStor
17695 | QA Problems | 84741 | MBLWHOI Library |   |   | Yes | BioStor
18262 | QA Problems | 84777 | MBLWHOI Library |   |   | Yes | BioStor
18270 | QA Problems | 84781 | MBLWHOI Library |   |   | Yes | BioStor
18295 | QA Problems | 84760 | MBLWHOI Library |   |   | Yes | BioStor
37032 | QA Problems | 99908 | MBLWHOI Library |   |   | Yes | BioStor
108590 | QA Problems | 223032 | MBLWHOI Library |   |   | Yes | BioStor
108670 | QA Problems | 221241 | MBLWHOI Library |   |   | Yes | BioStor
13999 | Removed | 89032 | Missouri Botanical Garden, Peter H. Raven Library |   |   | Yes | BioStor
119061 | QA Problems | 214425 | Museums Victoria |   |   | Yes | BioStor
119464 | QA Problems | 214426 | Museums Victoria |   |   | Yes | BioStor
119480 | QA Problems | 214164 | Museums Victoria |   |   | Yes | BioStor
120024 | QA Problems | 215248 | Museums Victoria |   |   | Yes | BioStor
120027 | QA Problems | 215247 | Museums Victoria |   |   | Yes | BioStor
120129 | QA Problems | 215356 | Museums Victoria |   |   | Yes | BioStor
43946 | QA Problems | 130127 | Smithsonian Libraries |   |   | Yes | BioStor
45820 | QA Problems | 214323 | Smithsonian Libraries |   |   | Yes | BioStor
51761 | Removed | 220052 | Smithsonian Libraries |   |   | Yes | BioStor
53247 | Removed | 55101 | Smithsonian Libraries |   |   | Yes | BioStor
53958 | Removed | 220033 | Smithsonian Libraries |   |   | Yes | BioStor
54505 | Removed | 220041 | Smithsonian Libraries |   |   | Yes | BioStor
105675 | QA Problems | 101305 | Smithsonian Libraries |   |   | Yes | BioStor
84743 | QA Problems | 183045 | University of Toronto - Gerstein Science Information Centre |   |   | Yes | BioStor
84745 | QA Problems | 30013 | University of Toronto - Gerstein Science Information Centre |   |   | Yes | BioStor
84770 | QA Problems | 18246 | University of Toronto - Gerstein Science Information Centre |   |   | Yes | BioStor
84776 | QA Problems | 37631 | University of Toronto - Gerstein Science Information Centre |   |   | Yes | BioStor

**Comment by rdmpage** [comment]
Hi @crowleyb I can't begin to describe how much this drives me crazy! For BHL to simply delete whole scans without thinking through the consequences is hugely frustrating. I have scripts that try and automate mitigate most of the damage this causes, but some articles require manually editing the database in order to fix the problem. This is tedious in the extreme, and not the best use of my time. Surely a better solution would be to preserve the PageIDs but replace the content those PageIDs link too? Deliberately breaking links is never a good idea.

**Comment by rdmpage** [comment]
@crowleyb OK, I think these "segments" have been fixed. There will be some lingering issues, such as pagination being interrupted by plates, but I don't have time to address this at the moment.
