### ISSUE TITLE
BHL segments - AG correspondence Part 1

### ISSUE THREAD

**Issue by drielinger** [rdmpage/biostor#68]
Rod:
Zip file with segments for a set of correspondence files for BHL.  Let me know if there is any problem with the formatting - I converted all to RIS instead of sending as a spreadsheet.  TY = letter.

Thanks

Diane Rielinger (Harvard Botany)
[Biostor1AG.zip](https://github.com/rdmpage/biostor/files/1081875/Biostor1AG.zip)

**Comment by rdmpage** [comment]
Hi Diane, Sorry for the delay in responding to this. I'll try and add these shortly. The RIS files have a bunch of problems, which I can fix here, but it's worth noting these for future reference. Did you try to open the RIS files in a program such as Endnote or Mendeley?

Each field needs to be of the form
```
XX  - value
```
that is, two character code, two spaces, hyphen, one space, then value.

Each record needs to be terminated by
```
ER  - 
```
that is, "ER", followed by two spaces, a hyphen, a single space, then a new line.

I use DP to indicate the contributor (not PB), and JO for the "journal", not T1. I realise that RIS fields are not always clearly defined, and people tend to use them in all sorts of ways.

**Comment by drielinger** [comment]
Rod:

Sorry about the errors.  I don’t have Endnote or Mendely so I didn’t try to open them.  Do you want me to fix them and resend to you?  I’m using a small Python program to automatically convert my .csv spreadsheets into RIS so it wouldn’t be any effort at all to change that and run the spreadsheets through again.

Thanks for all your help.

Diane

**Comment by rdmpage** [comment]
Hi Diane,

If it's no trouble to rerun the script that would be great.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by drielinger** [comment]
OK.  I’ll upload to GitHub as soon as I can.

Thanks

Diane

**Comment by drielinger** [comment]
New .zip file with changes made
[BioStor1.zip](https://github.com/rdmpage/biostor/files/1086271/BioStor1.zip)

**Comment by rdmpage** [comment]
Thans for the changes, I'm uploading these now. Almost done...
