### ISSUE TITLE
Define articles in BioStor and BHL for Occasional papers on mollusks, ISSN: 0073-0807

### ISSUE THREAD

**Issue by suwiding** [rdmpage/biostor#71]
@rdmpage I received 129 citations for this publication from the Ernst Mayr Library at the Museum of Comparative Zoology, Harvard University.  We eliminated all citations already defined in BioStor and BHL. The name of the library that contributed the citations is in the Database Provider (DP) field. Because the RIS is exported from EndNote, the starting and ending pages are in the same field. If this is a problem, I can post-process the RIS.  We didn't put the BHL pageids in the Notes field but can do that if needed. Thanks!

[opm2.zip](https://github.com/rdmpage/biostor/files/1167598/opm2.zip)

**Comment by rdmpage** [comment]
@suwiding Haven't had time to check for completeness but have added articles from the file.

**Comment by suwiding** [comment]
@rdmpage Thanks very much for your work on this.  I finally had a chance to look closely at the results and discovered a couple of problems.  None of the obituaries (about 4) were defined as articles.  I recently realized that obituaries for scientists in BHL are very useful to Wikipedia.  The reason they weren't defined in BioStor is almost definitely because roman numerals are used for the page numbers of obituaries in this publication. I used the manual method of defining them in BHL. They won't be visible until a nightly job runs.  If you want a list of the obituaries, I'm happy to provide one. The other, bigger problem is that volume 6 was never digitized so, of course, the article definition failed. I put in another request for digitization and hopefully it will happen soon. Thanks again.

**Comment by suwiding** [comment]
Volume 6, the final volume, was digitized and added to BHL.  The attached RIS file includes article metadata for volume 6 only.  The database provider field (DP) is populated but I didn't supply starting BHL pageids.  Thanks very much for your help!  
[opm3.txt](https://github.com/rdmpage/biostor/files/1258455/opm3.txt)

**Comment by rdmpage** [comment]
@suwiding Finally managed to add these, sorry for the delay.

**Comment by suwiding** [comment]
The articles look good in BHL.  Thanks!!
