### ISSUE TITLE
Memoirs of The National Museum of Victoria

### ISSUE THREAD

**Issue by rdmpage** [rdmpage/biostor#74]
Memoirs of The National Museum of Victoria, e.g. http://direct.biostor.org/reference/113337 has been replaced, breaking the articles

**Comment by nicolekearney** [comment]
Just checking in and wanted to clarify that only volumes 1-14 have been replaced in BHL (because they contained some blurry pages).

**Comment by rdmpage** [comment]
@nicolekearney This is partly a note to myself, I've fixed the articles. The think which drives me crazy is that when BHL replaces a scanned item all the PageIDs for that item vanish, breaking all the articles linked to that item. In an ideal world the PageIDs would be stable, or BHL would provide a mapping from old to new. As it stands, everything breaks and I have to go back and fix the BioStor articles. #nothappy
