### ISSUE TITLE
Article BioStor 114565. Pages changed at BHL.

### ISSUE THREAD

**Issue by suwiding** [rdmpage/biostor#81]
This article is still valid however the BHL item on which the article is defined will soon be replaced due to missing pages.  Article is defined on BHL item 41412 with a starting page of 11007109.  Replacement item is BHL 18609 with start page of 2110659. I have already moved the corresponding BHL article (part 79306).  We apologize for the inconvenience.

Title Die Amphipoden der Plankton-expedition. I. Theil. Hyperiidea. 1

**Comment by rdmpage** [comment]
@suwiding Many thanks for the heads up, I've updated BioStor to point to the new pages.
