### ISSUE TITLE
Problems with author names in articles within Carnivorous Plant Newsletter.

### ISSUE THREAD

**Issue by suwiding** [rdmpage/biostor#82]
A BHL user opened a help desk ticket with BHL to report problems with author names in articles defined in Carnivorous Plant Newsletter.  BHL bib record URL is https://www.biodiversitylibrary.org/bibliography/133901. For example, 'Iacute' is the named author in 6 articles.  BioStor author id 80513.  It appears that this was derived from the author name Lubomír Adamec.  Parsing this resulted in 3 different author names 'Lubom', 'Iacute' and Ademec.  Please let us know if you will fix this in BioStor.  If so, we'll wait for the fixes to be harvested into BHL.  If not, we'll manually update BHL.  Thanks! Susan

**Comment by rdmpage** [comment]
@suwiding Whoops, looks like the HTML code for í ```&iacute;``` got parsed as part of the author's name. Oh the joys of screen scraping to get metadata. I've manually fixed the six articles, thanks for spotting this.
