### ISSUE TITLE
Chandlerella inversa n. sp., Filaire parasite de Nectariniidés au Gabon 

### ISSUE THREAD

**Issue by cajunjoel** [rdmpage/biostor#89]
http://biostor.org/reference/250777
https://www.biodiversitylibrary.org/page/58041965

The metadata doesn't match the article. Is/was this due to a page addition? The article starts four pages later:
https://www.biodiversitylibrary.org/page/58041969

The PDF at IA needs updating as well.

**Comment by rdmpage** [comment]
HI @cajunjoel, this looks like one of a number of fails for this item :( Thanks for spotting it, I will investigate and fix when I get the chance.

**Comment by rdmpage** [comment]
@cajunjoel OK I think I've finally fixed this (and one other article in the same item that was also incorrect). I've noticed that the table of contents for this item in BHL [266101](https://www.biodiversitylibrary.org/item/266101) doesn't bear much relation to the articles in BioStor, maybe this will be sorted when @mlichtenberg runs the script that fetches new stuff form BioStor.
