### ISSUE TITLE
A revision of the North American species of Ichneumon-flies of the genus Odontomerus

### ISSUE THREAD

**Issue by cajunjoel** [rdmpage/biostor#90]
Hi Rod

Another article metadata issue

BioStor segment 70215 is pointing to the incorrect start page

https://www.biodiversitylibrary.org/part/41034#/summary

It should be pointing to: https://www.biodiversitylibrary.org/page/32382076

(from Diana Duncan)

**Comment by rdmpage** [comment]
@cajunjoel Thanks for catching this, my code for handling multiple articles with the same page within a single item clearly didn't work this time! I've updated the article in BioStor.
