### ISSUE TITLE
Metadata correction

### ISSUE THREAD

**Issue by cajunjoel** [rdmpage/biostor#92]
"On Neotropical Lycwiid**ce**, with Descriptions of New Species"
should be
"On Neotropical Lycwiid**æ**, with Descriptions of New Species"

Already corrected in BHL

**Comment by rdmpage** [comment]
This already been corrected in BioStor, but still seems to have the misspelt title in BHL (which was sourced from CrossRef). I think this is an example of BHL not updating title information it harvests from BioStor.
