### ISSUE TITLE
Incorrect Article Metadata:  ...Phyllocnistis citrella Stainton...

### ISSUE THREAD

**Issue by cajunjoel** [rdmpage/biostor#93]
"One new species and two new records of parasitoids of Phyllocnistis citrella Stainton (Hymenoptera: Eulophidae) from Jiangxi." 

The part metadata does not match up to page that it links to:

Part: https://www.biodiversitylibrary.org/part/36912
Page: https://www.biodiversitylibrary.org/page/2844769#page/110/mode/1up

**Comment by rdmpage** [comment]
@cajunjoel Strange because the metadata in BioStor matches the article. I've edited the date I BioStor to see if this gets bumped into Mike's harvest and maybe updates the title? If not, it will have to be edited directly in BHL.
