### ISSUE TITLE
BHL article with wrong author contributed by BioStor

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#94]
BHL article with wrong author contributed by BioStor: https://www.biodiversitylibrary.org/part/226006
Author is: https://myriatrix.myspecies.info/users/karl-wilhelm-verhoeff

**Comment by rdmpage** [comment]
@Archilegt Thanks for spotting this. Looks like the error comes from ZOBODAT, e.g. https://www.zobodat.at/publikation_articles.php?id=230214 which I used as the source of metadata to find these articles. Two others in the same series were also affected. I've updated BioStor for all three articles, hopefully the script @mlichtenberg uses to update BHL will pick these up.

**Comment by Archilegt** [comment]
Thank you, @rdmpage ! If you would like to update the article title as well, the full title is:
Beiträge zur Kenntniss paläarktischer Myriopoden. III. Aufsatz: Zusammenfassende Darstellung der Aufenthaltsorte der mitteleuropäischen Diplopoden.
Including the "III. Aufsatz" is important because there were a few articles in the series.

**Comment by Archilegt** [comment]
Publication re-checked on BHL next day (20.05.2022). Author is now “[Verhoeff, Karl W. (Karl Wilhelm) 1867-1945](https://www.biodiversitylibrary.org/creator/54751)”.

**Comment by rdmpage** [comment]
Great, it worked!

**Comment by Archilegt** [comment]
Zobodat notified on 25.05.2022. Author corrected on the same day by Michael Malicky to "[Karl Wilhelm [Carl] Verhoeff](https://www.zobodat.at/personen.php?id=4693)".
