### ISSUE TITLE
Duplicated DOIs and disconnected publications in BHL

### ISSUE THREAD

**Issue by Archilegt** [rdmpage/biostor#98]
Following the topic of Duplicated DOIs in:
https://iphylo.blogspot.com/2007/05/duplicate-dois.html
https://iphylo.blogspot.com/2013/05/duplicate-dois-for-same-article-issued.html
https://iphylo.blogspot.com/2022/02/duplicate-dois-again.html

This is related to the broader topic of disconnected publications in BHL, of which I have seen a few cases already. This case focus on three disconnected items in BHL, being the first and second editions of the "Exploration of the Red River of Louisiana, in the year 1852".

A copy of the first edition, contributed by the University of Toronto - Robarts Library, has BHL landing page and DOI at:
https://doi.org/10.5962/bhl.title.66388
This copy bears the long title.

There are two copies of the second edition, both with BHL landing pages and DOIs:
A copy contributed by the Library of Congress:
https://doi.org/10.5962/bhl.title.43982
A copy contributed by the Smithsonian Libraries
https://doi.org/10.5962/bhl.title.47030
These copies bear the short title.

What should happen is that all editions and versions get a landing page or, minimally, that 1) two landing pages for two versions are linked to each other and 2) the two versions of the second edition are merged together under one DOI. However, metadata also requires curation, as the version of the first edition bears the long title and the two versions of the second edition have the short title.

Task for me: Try finding the related reports of the congress sessions of the Senate / House of Representatives for better documenting publication dates. I think that I already did this in the past, when at the Smithsonian in 2017. EDIT: This is anyway reflected on page ii of the first edition (https://www.biodiversitylibrary.org/page/42271829): "February 4, 1853. — Ordered to be printed.  March 10. — Ordered that 2,000 additional copies be printed, 200 of which for Captain Marcy." and "War Department, Washington November 8, 1853..."

**Related issue:**
Lack of clarification on publications and editions like the above may lead to incorrect publication dates for species in databases. In this case the first edition of course has priority (1853) over the second edition (1854), but that may not be evident to external users if the items remain disconnected. Species names and descriptions were published as new in both editions, and in different pages, which is related to the topic of connecting species names to their original publication and page. 
**See example for _Scolopendra heros_:**
First edition, University of Toronto: 
Page **272**: https://www.biodiversitylibrary.org/page/42272059
Plate XVIII: https://www.biodiversitylibrary.org/page/42272192
Second edition, Library of Congress:
Page **243**: https://www.biodiversitylibrary.org/page/30280347
Plate XVIII: https://www.biodiversitylibrary.org/page/30280485
Second edition, Smithsonian Libraries:
Page **243**: https://www.biodiversitylibrary.org/page/32657755
Plate XVIII: https://www.biodiversitylibrary.org/page/32657893

This is also related to the topic that I discussed with @udcmrk during TDWG 2021: we need a unique pointer for the same scanned printed page in BHL, regardless of how many scanned versions a page may have.

@rdmpage, @mlichtenberg, @udcmrk, thoughts on this?

**Comment by rdmpage** [comment]
@Archilegt Thanks for the detailed comment. This is timely as BHL is starting to think about how to handle multiple copies of the "same" thing. I've shared this on a BHL chat that discusses persistent identifiers. Perhaps there will also be some discussion here.

**Comment by Archilegt** [comment]
Feedback sent to BHL. It has become incredibly difficult to find their contact form. Maybe BHL doesn't want to be contacted at all?

**Comment by rdmpage** [comment]
@Archilegt You are not wrong. Enabling feedback assumes there is some one to respond to that feedback, and my understanding is that BHL doesn't have the resources for that at the moment, hence the contact form is less prominent than it used to be.
